GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info 

###
GET http://localhost:3001/api/persons/6881

###
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Mary Poppendieck", 
    "number": "39-23-6423122"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Shawn Spencer1234ss", 
    "number": "39-23-6423122"
}

###
GET http://localhost:3001/api/persons/2953

###
DELETE http://localhost:3001/api/persons/2953

