GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info 

###
GET http://localhost:3001/api/persons/67a9d1519529ddc784f91c9d

###
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Mary Poppendieck", 
    "number": "39-23-6423122"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Claw Man", 
    "number": "111-222-3333"
}

###
GET http://localhost:3001/api/persons/67a9d18f9529ddc784f91ca1

###
DELETE http://localhost:3001/api/persons/2953

